---

- name: install software packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - openstack-trove-api
  - openstack-trove-conductor
  - openstack-trove-taskmanager
  notify:
  - sync trove database

- name: update trove config
  template:
    src: trove.conf.j2
    dest: /etc/trove/trove.conf
  notify:
  - restart openstack-trove-api service
  - restart openstack-trove-conductor service
  - restart openstack-trove-taskmanager service

- name: update trove conductor config
  template:
    src: trove-conductor.conf.j2
    dest: /etc/trove/trove-conductor.conf
  notify:
  - restart openstack-trove-api service
  - restart openstack-trove-conductor service
  - restart openstack-trove-taskmanager service

- name: update trove taskmanager config
  template:
    src: trove-taskmanager.conf.j2
    dest: /etc/trove/trove-taskmanager.conf
  notify:
  - restart openstack-trove-api service
  - restart openstack-trove-conductor service
  - restart openstack-trove-taskmanager service

- name: update trove guestagent config
  template:
    src: trove-guestagent.conf.j2
    dest: /etc/trove/trove-guestagent.conf

- name: enable openstack-trove-api service
  service:
    name: openstack-trove-api
    enabled: yes

- name: enable openstack-trove-conductor service
  service:
    name: openstack-trove-conductor
    enabled: yes

- name: enable openstack-trove-taskmanager service
  service:
    name: openstack-trove-taskmanager
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
