---

- name: install software packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - neutron-plugin-ml2
  - neutron-openvswitch-agent
  - manila-share
  - python-pymysql

- name: copy manila ssh private key
  copy:
    src: id_rsa
    dest: /etc/manila/id_rsa
    owner: manila
    group: manila

- name: copy manila ssh public key
  copy:
    src: id_rsa.pub
    dest: /etc/manila/id_rsa.pub
    owner: manila
    group: manila

- name: start openvswitch service
  service:
    name: openvswitch-switch
    state: started

- name: create data bridge
  openvswitch_bridge:
    bridge: br-dat
    state: present

- name: add data bridge interface
  openvswitch_port:
    bridge: br-dat
    port: eth-data
    state: present

- name: update neutron config
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
  - restart neutron-openvswitch-agent service

- name: update ml2 plugin config
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify:
  - restart neutron-openvswitch-agent service

- name: update openvswitch agent config
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  notify:
  - restart neutron-openvswitch-agent service

- name: update manila config
  template:
    src: manila.conf.j2
    dest: /etc/manila/manila.conf
  notify:
  - restart manila-share service

- name: enable openvswitch service
  service:
    name: openvswitch-switch
    enabled: yes

- name: enable neutron-openvswitch-agent service
  service:
    name: neutron-openvswitch-agent
    enabled: yes

- name: enable manila-share service
  service:
    name: manila-share
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
