---

- name: install software packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - openstack-neutron
  - openstack-neutron-ml2
  - openstack-neutron-linuxbridge
  - conntrack-tools

- name: create linuxbridge service override folder
  file:
    path: /etc/systemd/system/neutron-linuxbridge-agent.service.d
    state: directory
  when: lxd_linuxbridge_service_override is defined and lxd_linuxbridge_service_override
  notify:
  - systemd daemon reload

- name: create linuxbridge service override
  copy:
    src: linuxbridge.override.conf
    dest: /etc/systemd/system/neutron-linuxbridge-agent.service.d/override.conf
  when: lxd_linuxbridge_service_override is defined and lxd_linuxbridge_service_override
  notify:
  - systemd daemon reload

- name: update default plugin link
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link
    force: yes

- name: update neutron config
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
  - restart neutron-linuxbridge-agent service
  - restart neutron-metadata-agent service
  - restart neutron-dhcp-agent service
  - restart neutron-l3-agent service

- name: update ml2 plugin config
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify:
  - restart neutron-linuxbridge-agent service
  - restart neutron-metadata-agent service
  - restart neutron-dhcp-agent service
  - restart neutron-l3-agent service

- name: update linuxbridge agent config
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  notify:
  - restart neutron-linuxbridge-agent service

- name: update metadata agent config
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
  notify:
  - restart neutron-metadata-agent service

- name: update dhcp agent config
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
  notify:
  - restart neutron-dhcp-agent service

- name: update l3 agent config
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
  notify:
  - restart neutron-l3-agent service

- name: enable neutron-linuxbridge-agent service
  service:
    name: neutron-linuxbridge-agent
    enabled: yes

- name: enable neutron-metadata-agent service
  service:
    name: neutron-metadata-agent
    enabled: yes

- name: enable neutron-dhcp-agent service
  service:
    name: neutron-dhcp-agent
    enabled: yes

- name: enable neutron-l3-agent service
  service:
    name: neutron-l3-agent
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
