---

- name: install software packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - openstack-neutron-ml2
  - openstack-neutron-linuxbridge
  - openstack-manila-share

- name: create linuxbridge service override folder
  file:
    path: /etc/systemd/system/neutron-linuxbridge-agent.service.d
    state: directory
  when: lxd_linuxbridge_service_override is defined and lxd_linuxbridge_service_override
  notify:
  - systemd daemon reload

- name: create linuxbridge service override
  copy:
    src: linuxbridge.override.conf
    dest: /etc/systemd/system/neutron-linuxbridge-agent.service.d/override.conf
  when: lxd_linuxbridge_service_override is defined and lxd_linuxbridge_service_override
  notify:
  - systemd daemon reload

- name: update default plugin link
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link
    force: yes

- name: copy manila ssh private key
  copy:
    src: id_rsa
    dest: /etc/manila/id_rsa
    owner: manila
    group: manila

- name: copy manila ssh public key
  copy:
    src: id_rsa.pub
    dest: /etc/manila/id_rsa.pub
    owner: manila
    group: manila

- name: update neutron config
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
  - restart neutron-linuxbridge-agent service

- name: update ml2 plugin config
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify:
  - restart neutron-linuxbridge-agent service

- name: update linuxbridge agent config
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  notify:
  - restart neutron-linuxbridge-agent service

- name: create manila state folder
  file:
    path: /var/lib/manila
    state: directory
    owner: manila
    group: manila

- name: update manila config
  template:
    src: manila.conf.j2
    dest: /etc/manila/manila.conf
  notify:
  - restart openstack-manila-share service

- name: enable neutron-linuxbridge-agent service
  service:
    name: neutron-linuxbridge-agent
    enabled: yes

- name: enable openstack-manila-share service
  service:
    name: openstack-manila-share
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
