---

- name: restart ntp service
  service:
    name: ntp
    state: restarted

- name: restart chrony service
  service:
    name: chronyd
    state: restarted

- name: restart ntpd service
  service:
    name: ntpd
    state: restarted
