---

- name: install software packages
  zypper:
    name: rabbitmq-server
    state: latest

- name: update rabbitmq env config
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: rabbitmq
    group: rabbitmq
  notify:
  - restart rabbitmq service

- name: enable rabbitmq service
  service:
    name: rabbitmq-server
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers

- name: add rabbitmq user
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
