---

- name: install software packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - nova-compute-lxd
  - neutron-plugin-ml2
  - neutron-linuxbridge-agent

- name: update nova config
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
  notify:
  - restart nova-compute service

- name: remove nova-compute config
  file:
    path: /etc/nova/nova-compute.conf
    state: absent
  notify:
  - restart nova-compute service

- name: update neutron config
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
  - restart neutron-linuxbridge-agent service

- name: update ml2 plugin config
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify:
  - restart neutron-linuxbridge-agent service

- name: update linuxbridge agent config
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  notify:
  - restart neutron-linuxbridge-agent service

- name: enable nova-compute service
  service:
    name: nova-compute
    enabled: yes

- name: enable neutron-linuxbridge-agent service
  service:
    name: neutron-linuxbridge-agent
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
