---

- name: sync glance database
  command: /usr/bin/glance-manage db_sync
  become: true
  become_method: su
  become_user: glance
  become_flags: '-s /bin/bash'
  run_once: true

- name: import metadata definetions
  command: /usr/bin/glance-manage db_load_metadefs /etc/glance/metadefs
  become: true
  become_method: su
  become_user: glance
  become_flags: '-s /bin/bash'
  run_once: true

- name: restart glance-api service
  service:
    name: glance-api
    state: restarted

- name: restart glance-registry service
  service:
    name: glance-registry
    state: restarted

- name: restart openstack-glance-api service
  service:
    name: openstack-glance-api
    state: restarted

- name: restart openstack-glance-registry service
  service:
    name: openstack-glance-registry
    state: restarted
