---

- name: install software packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - openstack-nova-compute
  - openstack-neutron-ml2
  - patch

- name: copy dvs software source
  copy:
    src: networking-vsphere-stable-newton.tar.gz
    dest: /tmp/networking-vsphere-stable-newton.tar.gz
  changed_when: false

- name: copy dvs software patch 45dd174e
  copy:
    src: patch-45dd174e.diff
    dest: /var/tmp/patch-45dd174e.diff
  changed_when: false

- name: copy dvs service file
  copy:
    src: centos/dvs-agent.service
    dest: /usr/lib/systemd/system/neutron-dvs-agent.service

- name: install dvs software
  shell: |
    mkdir /tmp/networking-vsphere
    tar zxf /tmp/networking-vsphere-stable-newton.tar.gz -C /tmp/networking-vsphere --strip-components=1
    cd /tmp/networking-vsphere
    sed -i -e 's/cfg\.CONF\.DVS_AGENT\.report_interval/cfg.CONF.AGENT.report_interval/g' networking_vsphere/agent/dvs_neutron_agent.py
    python setup.py install --install-data / --record ../networking-vsphere-files
    patch -b -p 1 -N -i /var/tmp/nova.patch -d /usr/lib/python2.7/site-packages
    patch -b -p 1 -N -i /var/tmp/patch-45dd174e.diff -d /usr/lib/python2.7/site-packages
    chown root:neutron /etc/neutron/ml2_conf_vmware_dvs.ini
    chmod 640 /etc/neutron/ml2_conf_vmware_dvs.ini
  args:
    creates: /usr/bin/neutron-dvs-agent
  notify:
  - restart openstack-nova-compute service

- name: update default plugin link
  file:
    src: /etc/neutron/ml2_conf_vmware_dvs.ini
    dest: /etc/neutron/plugin.ini
    state: link
    force: yes

- name: update nova config
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
  notify:
  - restart openstack-nova-compute service

- name: update neutron config
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
  - restart neutron-dvs-agent service

- name: update dvs agent config
  template:
    src: ml2_conf_vmware_dvs.ini.j2
    dest: /etc/neutron/ml2_conf_vmware_dvs.ini
  notify:
  - restart neutron-dvs-agent service

- name: enable openstack-nova-compute service
  service:
    name: openstack-nova-compute
    enabled: yes

- name: enable neutron-dvs-agent service
  service:
    name: neutron-dvs-agent
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
