---

- name: sync keystone database
  command: /usr/bin/keystone-manage db_sync
  become: true
  become_method: su
  become_user: keystone
  become_flags: '-s /bin/bash'
  run_once: true

- name: setup fernet repository
  command: /usr/bin/keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  run_once: true

- name: setup fernet keys
  command: /usr/bin/keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  run_once: true

- name: setup pki signing
  command: /usr/bin/keystone-manage pki_setup --keystone-user keystone --keystone-group keystone
  run_once: true

- name: bootstrap keystone
  command: >
    /usr/bin/keystone-manage bootstrap
    --bootstrap-password "{{ keystone_admin_password }}"
    --bootstrap-admin-url "{% if stack_ssl_enabled %}https{% else %}http{% endif %}://{{ stack_management_ipaddress }}:35357/v3"
    --bootstrap-internal-url "{% if stack_ssl_enabled %}https{% else %}http{% endif %}://{{ stack_management_ipaddress }}:5000/v3"
    --bootstrap-public-url "{% if stack_ssl_enabled %}https{% else %}http{% endif %}://{{ stack_access_ipaddress }}:5000/v3"
    --bootstrap-region-id "{{ keystone_region_name }}"
  run_once: true

- name: restart apache2 service
  service:
    name: apache2
    state: restarted

- name: restart httpd service
  service:
    name: httpd
    state: restarted
