---

- name: sync nova api database
  command: /usr/bin/nova-manage api_db sync
  become: true
  become_method: su
  become_user: nova
  become_flags: '-s /bin/bash'
  run_once: true

- name: sync nova database
  command: /usr/bin/nova-manage db sync
  become: true
  become_method: su
  become_user: nova
  become_flags: '-s /bin/bash'
  run_once: true

- name: restart nova-api service
  service:
    name: nova-api
    state: restarted

- name: restart nova-conductor service
  service:
    name: nova-conductor
    state: restarted

- name: restart nova-consoleauth service
  service:
    name: nova-consoleauth
    state: restarted

- name: restart nova-scheduler service
  service:
    name: nova-scheduler
    state: restarted

- name: restart nova-novncproxy service
  service:
    name: nova-novncproxy
    state: restarted

- name: restart nova-serialproxy service
  service:
    name: nova-serialproxy
    state: restarted

- name: restart openstack-nova-api service
  service:
    name: openstack-nova-api
    state: restarted

- name: restart openstack-nova-conductor service
  service:
    name: openstack-nova-conductor
    state: restarted

- name: restart openstack-nova-consoleauth service
  service:
    name: openstack-nova-consoleauth
    state: restarted

- name: restart openstack-nova-scheduler service
  service:
    name: openstack-nova-scheduler
    state: restarted

- name: restart openstack-nova-novncproxy service
  service:
    name: openstack-nova-novncproxy
    state: restarted

- name: restart openstack-nova-serialproxy service
  service:
    name: openstack-nova-serialproxy
    state: restarted
