---

- name: install software packages
  yum:
    name: rsyslog
    state: latest

- name: update rsyslog stack config
  template:
    src: centos/stack.conf.j2
    dest: /etc/rsyslog.d/stack.conf
  notify:
  - restart rsyslog service

- name: enable rsyslog service
  service:
    name: rsyslog
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
