---

- name: gather machine facts
  vmware_guest_facts:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ vcenter_vm_machines_folder }}"
    name: "{{ machine.name }}"
  register: machine_facts
  changed_when: false
  ignore_errors: true
  when:
  - machine.provision

- name: create temp folder
  tempfile:
    prefix: "esx.create.{{ machine.name }}."
    state: directory
  register: temp_folder
  when:
  - machine.provision
  - machine_facts | failed

- name: create machine provisioning tasks
  template:
    src: opensuse/esx-ansible-create.yml.j2
    dest: "{{ temp_folder.path }}/create.yml"
  when:
  - machine.provision
  - machine_facts | failed

- name: run machine provisioning tasks
  include: "{{ temp_folder.path }}/create.yml"
  when:
  - machine.provision
  - machine_facts | failed

- name: create machine dns record
  nsupdate:
    server: "{{ master_management_ipaddress }}"
    zone: "{{ management_domain }}"
    record: "{{ machine.name }}"
    type: A
    value: "{{ machine | json_query(query) | join }}"
  vars:
    query: "nics[?network=='management'].ipaddress"

- name: create machine dns ptr record
  nsupdate:
    server: "{{ master_management_ipaddress }}"
    zone: "{{ management_arpa }}"
    record: "{{ machine | json_query(query) | join | ipaddr('revdns') }}"
    type: PTR
    value: "{{ machine.name }}.{{ management_domain }}."
  vars:
    query: "nics[?network=='management'].ipaddress"

- name: gather machine facts
  vmware_guest_facts:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ vcenter_vm_machines_folder }}"
    name: "{{ machine.name }}"
  register: machine_facts
  changed_when: false
  when:
  - machine.provision

- name: create host_vars folder
  file:
    path: "{{ work_folder }}/inventory/host_vars"
    state: directory

- name: update machine host_vars file
  template:
    src: esx-ansible-hostvars.j2
    dest: "{{ work_folder }}/inventory/host_vars/{{ machine.name }}.{{ management_domain }}"
