---

- name: gather machine facts
  shell: "lxc config show {{ machine.name }}"
  register: machine_facts
  changed_when: false
  ignore_errors: true
  when:
  - machine.provision

- name: "delete {{ machine.name }}"
  lxd_container:
    name: "{{ machine.name }}"
    state: absent
    force_stop: true
    url: "{{ lxd_remote_url }}"
    trust_password: "{{ lxd_remote_password }}"
  when:
  - machine.provision
  - machine_facts | success

- name: delete machine dns record
  nsupdate:
    server: "{{ master_management_ipaddress }}"
    zone: "{{ management_domain }}"
    record: "{{ machine.name }}"
    type: A
    state: absent

- name: delete machine dns ptr record
  nsupdate:
    server: "{{ master_management_ipaddress }}"
    zone: "{{ management_arpa }}"
    record: "{{ machine | json_query(query) | join | ipaddr('revdns') }}"
    type: PTR
    state: absent
  vars:
    query: "nics[?network=='management'].ipaddress"

- name: delete machine host_vars file
  file:
    path: "{{ work_folder }}/inventory/host_vars/{{ machine.name }}.{{ management_domain }}"
    state: absent
