---

- name: install software packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - openstack-glance
  notify:
  - sync glance database
  - import metadata definetions

- name: update glance-api config
  template:
    src: glance-api.conf.j2
    dest: /etc/glance/glance-api.conf
  notify:
  - restart openstack-glance-api service

- name: update glance-registry config
  template:
    src: glance-registry.conf.j2
    dest: /etc/glance/glance-registry.conf
  notify:
  - restart openstack-glance-registry service

- name: enable openstack-glance-api service
  service:
    name: openstack-glance-api
    enabled: yes

- name: enable openstack-glance-registry service
  service:
    name: openstack-glance-registry
    enabled: yes

- name: run queued handlers
  meta:
    flush_handlers
