---

- name: install software packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - ntp
  - ntpdate
  when: ntp_timesync

- name: update ntp config
  template:
    src: ubuntu/ntp.conf.j2
    dest: /etc/ntp.conf
  when: ntp_timesync
  notify:
  - restart ntp service

- name: enable ntp service
  service:
    name: ntp
    enabled: yes
  when: ntp_timesync

- name: run queued handlers
  meta:
    flush_handlers

- name: update timezone
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
